// flow-typed signature: 5b6a87588a72f9f2ce5f2c33907c0fc5
// flow-typed version: <<STUB>>/normalize.css_v7.x.x/flow_v0.57.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   'normalize.css'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'normalize.css' {
  declare module.exports: any;
}
