
export enum ActionTypes {
   ADD_TODO = "ADD_TODO",
   DELETE_TODO = "DELETE_TODO",
   EDIT_TODO = "EDIT_TODO",
   MARK_TODO = "MARK_TODO",
   MARK_ALL = "MARK_ALL",
   CLEAR_MARKED = "CLEAR_MARKED",
   CHANGE_THEME = "CHANGE_THEME",
}